#!/usr/bin/env bash
# The script that accepts two arguments

domain=$1
if [ "$#" -eq 2 ]; then
   sudo sub=$2
else
  sub=("www" "lb-01" "web-01" "web-02")
fi
for subdomain in "${sub[@]}"; do
    sudo echo -n "The subdomain $subdomain"
    sudo dig "$subdomain.$domain" | grep -A1 'ANSWER SECTION:' | tail -n -1 | awk '{ print " is a " $4 " record and points to " $5}'
done